### PR TITLE
Add OpenMandriva vendor to dnf backend

### PR DESCRIPTION
**Pull request by berolinux**
Signed-off-by: Bernhard Rosenkränzer <bero@lindev.ch>

### CODE REVIEW

**Comment by berolinux** [comment]
Cc @Conan-Kudo

**Comment by Conan-Kudo** [comment]
@berolinux  Overall, looks good. One question: I note that you have a `contrib` repo. Do you want PackageKit to consider that an "official" source?

**Comment by Conan-Kudo** [comment]
@hughsie This PR obsoletes #139.

**Comment by Conan-Kudo** [comment]
Ah, wait, I see contrib is supported. Looks good!

**Comment by berolinux** [comment]
Yes, contrib is (semi-)official. It's official packages that receive less attention than main ones.

**Comment by Conan-Kudo** [comment]
Okay, cool. 👍

**Comment by Conan-Kudo** [comment]
Actually, looks like @kalev was the last person to touch the DNF backend. @kalev could you review this?

**Comment by Conan-Kudo** [comment]
@berolinux You may want to rework the commit message title to be prefixed by `dnf:` since that's how other commits to the backend look: https://github.com/hughsie/PackageKit/commits/master/backends/dnf

**Comment by kalev** [comment]
+1 from me, thanks!

**Pull request merged**
