### PR TITLE
add OpenMandriva support to libhif backend

### PR DESCRIPTION
**Pull request by tpgxyz**
Hi,

i've added support for OpenMandriva distribution.
@Conan-Kudo

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
Looks good to me! 👍 

@hughsie: what do you think of it?

**Comment by hughsie** [comment]
LGTM.

**Comment by Conan-Kudo** [comment]
@tpgxyz Are you sure your repository setup is correct?

Keep in mind that these are matching IDs used in repo files. You can see an example of what they correspond to with [a paste of mageia-x86_64.repo from Mageia Cauldron's /etc/yum.repos.d](https://paste.fedoraproject.org/387707/87332146/) and [the Mageia vendor file for the Hif backend](https://github.com/hughsie/PackageKit/blob/master/backends/hif/hif-backend-vendor-mageia.c).

**Comment by tpgxyz** [comment]
@Conan-Kudo Hi, i've updated my PR, please review.

**Comment by berolinux** [comment]
OpenMandriva has switched to dnf -- this is superseded by https://github.com/hughsie/PackageKit/pull/248 (but might still be useful in order to support older releases)

**Comment by Conan-Kudo** [comment]
@berolinux The hif backend has been removed several releases ago.

**Pull request closed without merging**
