### PR TITLE
cnf: zsh command_not_found_handler should return the same as its bash equivalent

### PR DESCRIPTION
**Pull request by timspeetjens**

### CODE REVIEW

**Comment by hughsie** [comment]
3ad2c60fc9059998f314df33b59c97eb2f237782 seemed to suggest 127 was the right value...

**Comment by timspeetjens** [comment]
The documentation (http://zsh.sourceforge.net/Doc/Release/Command-Execution.html) says it should return 0 if it successfully handled the command, or non-zero otherwise. In that case, the zsh itself returns 127 after printing a file not found message.

I think zsh should revise its behaviour, but that's beyond the scope of this issue / PR.

This PR fixes #134

**Comment by timspeetjens** [comment]
As per http://www.zsh.org/mla/workers/2016/msg02049.html bash and zsh will behave equally, though the name difference will be maintained, starting from zsh 5.2

**Comment by hughsie** [comment]
So this PR can be closed?

**Comment by timspeetjens** [comment]
The referenced change in zsh does not change the issue or its solution.

**Pull request merged**
