### PR TITLE
- Initial support to comps xml parsing. Enable hif backend to search

### PR DESCRIPTION
**Pull request by heliocastro**
categories and do a simple category mapping.
TODO:
- Add dynamic categories
- Replace package query function to a proper libhif function

Signed-off-by: Helio Chissini de Castro <helio@kde.org>

### CODE REVIEW

**Comment by kkofler** [comment]
I still count 5 open issues (you fixed 1 issue completely and 1 only partially), can you please have another look?

**Comment by kkofler** [comment]
@hughsie: The issues you pointed out should be addressed now, can this please be merged now?

**Comment by kkofler** [comment]
@hughsie: Ping?

**Comment by hughsie** [comment]
I'm going to review this after the next release; the current list of changes in the release is already too high, and I need to get an easy-to-QA release out to fix some libhif issues. I'll aim to review/merge this again next week.

**Comment by kkofler** [comment]
@hughsie: Re-ping? Almost 4 weeks have passed.

**Comment by kkofler** [comment]
@heliocastro: I just wanted to do a test build with your latest patchset, but it does not compile!
```
pk-backend-hif.c: In function 'pk_backend_get_groups_from_category':
pk-backend-hif.c:1285:12: error: 'groups' undeclared (first use in this function)
     return groups;
            ^
pk-backend-hif.c:1285:12: note: each undeclared identifier is reported only once for each function it appears in
```
Haven't you tested this? We need to make sure this 1. compiles and 2. actually works in Apper.

**Comment by kkofler** [comment]
@hughsie: The compilation error should be fixed with the above commit (from February 18) (it was a mistake in one of the requested cleanups), now can you PLEASE merge this? Over 3 weeks passed again.

This feature is very important to us Fedora KDE developers, and yet we have been waiting for it for almost a year now, and this pull request has been open for over 3 months.

**Comment by hughsie** [comment]
@heliocastro Can you merge all your patches down into one patch please, and then I can review it again. There are a few little issue, but I can't tell what was fixed in the subsequent patches.

@kkofler I'll merge it when it's ready.

**Comment by kkofler** [comment]
@hughsie: OK, I'll prepare a squashed commit, I think it'll be easier for everyone that way. (Helio does not want to work on this anymore, and I don't want to block on him again. We lost way too much time already.)

**Comment by kkofler** [comment]
Superseded by pull request #49.

**Pull request closed without merging**
