### PR TITLE
Fix some bashism: echo -e is not POSIX

### PR DESCRIPTION
**Pull request by DimStar77**

### CODE REVIEW

**Comment by hughsie** [comment]
I assume make check still passes?

**Comment by DimStar77** [comment]
let me make a quick test run to re-confirm

**Comment by DimStar77** [comment]
ermm... it crashes the same way as without my diff

**Comment by DimStar77** [comment]
>FAIL: pk-test-daemon
====================

/packagekit-glib2/control: 12:31:48	PackageKit	notify::connected
12:31:48	PackageKit	tid = /13_accbcdea
12:31:48	PackageKit	got tid in 0.000000
12:31:48	PackageKit	getting #1
12:31:48	PackageKit	getting #2
12:31:48	PackageKit	getting #3
12:31:48	PackageKit	getting #4
12:31:48	PackageKit	getting #5
12:31:48	PackageKit	tid = /14_ddeceacc
12:31:48	PackageKit	tid = /15_cbadcbbc
12:31:48	PackageKit	tid = /16_adcaccec
12:31:48	PackageKit	tid = /17_deecaeea
12:31:48	PackageKit	tid = /18_ccaaddbd
12:31:48	PackageKit	got 5 tids in 0.000000
**
PackageKit:ERROR:pk-test-daemon.c:795:pk_test_control_get_properties_cb: assertion failed (text == "application/x-rpm;application/x-deb"): ("application/x-rpm" == "application/x-rpm;application/x-deb")
FAIL pk-test-daemon (exit status: 134)

is what I get in the log on 'master', just for reference for now

**Pull request closed without merging**
