### PR TITLE
Pacman 4.2 support

### PR DESCRIPTION
**Pull request by piernov**
I'm not sure about all the g_return_if_fail().
Most of the changes are inspired from pacman 4.2 's  src/pacman/callback.c

### CODE REVIEW

**Comment by fbourigault** [comment]
If backward compatibility is required, contributions are welcome !

**Comment by fbourigault** [comment]
@hughsie is it possible to have a bugfix release ? This will allow PackageKit to be back in Arch Linux repositories !

**Comment by eworm-de** [comment]
I think we still suffer the update problems, no?

**Comment by fbourigault** [comment]
If you mean #15, then yes but PackageKit was in official repos even wiht this known bug. It's my next task but I don't know when it will be ok.

**Comment by eworm-de** [comment]
No, #15 is not what I mean. I've described the problem above:

* Installing packages works, though package is installed, then reinstalled.
* Updates are not installed. Packagekit is busy for some time, then lists the same available updates again.

piernov reported the same, see Arch Linux forum link.

**Pull request merged**
