### PR TITLE
alpm: honor simulation when installing packages

### LINKED ISSUE #36: alpm: simulation install packages
I don't have bijiben installed on my system. By running `pkcon install bijiben` and answering `No` to abort the package installation, the package is installed anyway. As a first thought I think simulation installed the package.

### PR DESCRIPTION
**Pull request by fbourigault**
Fix #36 

Before this fix I was asked to proceed or not with installation. With this code, I'm no longer asked for confirmation. I think it was a question from libalpm and now with the right workflow there is no more question.

### CODE REVIEW

**Comment by ximion** [comment]
Does the simulate action emit packages and state information?

**Comment by fbourigault** [comment]
I found this function https://github.com/hughsie/PackageKit/blob/master/backends/alpm/pk-alpm-transaction.c#L951 which was not used anywhere in the backend code. Seems to be the job to do when running simulate action.

**Comment by fbourigault** [comment]
I pushed a new version of the fix. This seems to looks good

Declined installation:
```
$ ./pkcon install gcompris
Resolving                     [=========================]         
Querying                      [=========================]         
Testing changes               [=========================]         
Finished                      [                         ] (0%)  
The following packages have to be installed:
 gstreamer0.10-0.10.36-4.x86_64	GStreamer Multimedia Framework
 gstreamer0.10-base-0.10.36-3.x86_64	GStreamer Multimedia Framework Base plugin libraries
 gstreamer0.10-base-plugins-0.10.36-3.x86_64	GStreamer Multimedia Framework Base Plugins (gst-plugins-base)
 gcompris-data-14.07-1.any	Data files for GCompris
Proceed with changes? [N/y] 

The transaction did not proceed.
                              [=========================]         
Fatal error: user declined simulation
```

Accepted installation:
```
$ ./pkcon install gcompris
Resolving                     [=========================]         
Querying                      [=========================]         
Testing changes               [=========================]         
Finished                      [                         ] (0%)  
The following packages have to be installed:
 gstreamer0.10-0.10.36-4.x86_64	GStreamer Multimedia Framework
 gstreamer0.10-base-0.10.36-3.x86_64	GStreamer Multimedia Framework Base plugin libraries
 gstreamer0.10-base-plugins-0.10.36-3.x86_64	GStreamer Multimedia Framework Base Plugins (gst-plugins-base)
 gcompris-data-14.07-1.any	Data files for GCompris
Proceed with changes? [N/y] y

                              [=========================]         
Testing changes               [=========================]         
Installing                    [=========================]         
Waiting for authentication    [=========================]         
Starting                      [=========================]         
Resolving dependencies        [=========================]         
Downloading packages          [=========================]         
Checking signatures           [=========================]         
Starting                      [=========================]         
Testing changes               [=========================]         
Installing packages           [=========================]         
Finished                      [=========================]
```

**Comment by ximion** [comment]
Yes, that's much better :-) Looks like it should look like.

**Pull request merged**
