### PR TITLE
Fix hangs in packagekit-glib2 client if daemon crashes

### PR DESCRIPTION
**Pull request by pwithnall**
See the commit messages for details.

This may fix https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1118 (but I’m not entirely certain about it).

### CODE REVIEW

**Comment by pwithnall** [comment]
Currently only compile-tested. I’m testing it now.

**Comment by pwithnall** [comment]
Seems to fix the case of multiple hung calls to `pk_client_refresh_cache()` queueing up in multiple worker threads in gnome-software if I call `sudo systemctl kill packagekit.service` while gnome-software is searching for updates (thanks to Milan for the reproducer instructions).

**Comment by ximion** [comment]
The patch overall looks good to me! (I haven't tested it locally though)

I wonder whether there is any value in returning a dedicated "internal error"/"daemon crashed" error type here, so the GUI can show an appropriate message telling the user the failure wasn't their fault and they should try again or report a bug (as "daemon crash" is rather cryptic). On the other hand though, any such message would also be kind of horrible in a GUI to have in general, so I'm not sure if we need this or if it's even a good idea.

**Comment by hughsie** [comment]
I think we should get a nag from something like abrt in this case async from what PK does. Good work @pwithnall !

**Comment by hughsie** [comment]
> Seems to fix the case of multiple hung calls

I had the suspicion this was the cause a few weeks ago, but never got around to debugging it fully. I really appreciate the help! I'll do a tarball next week and we can put it in Fedora.

**Pull request merged**
