### PR TITLE
Add getters for PkProgress

### PR DESCRIPTION
**Pull request by robert-ancell**
Makes it easier to be type-safe and works better with language bindings.

### CODE REVIEW

**Comment by ximion** [comment]
Wouldn't this be `Since: 1.0.12`? (1.0.12 hasn't been released yet, current release is 1.0.11)
Change looks reasonable to me, but @hughsie has the final word :-)

**Comment by robert-ancell** [comment]
I was just about to ask someone to check that, as I wasn't sure. I'll update it.

**Comment by hughsie** [comment]
Can you rebase these together please, with that +1, thanks.

**Comment by robert-ancell** [comment]
Merged as requested

**Pull request closed without merging**
