### PR TITLE
zypp: PK_FILTER_ENUM_ARCH is supposed to filter on primary arch

### PR DESCRIPTION
**Pull request by DimStar77**

### CODE REVIEW

**Comment by DimStar77** [comment]
@mlandres would be nice if you could confirm that this does not cause weird issues for openSUSE / SUSE Linux (but as far as I understand, this should have been the meaning of this filter)

**Comment by mlandres** [comment]
Well, I can't tell whether  this will cause issues, as I do not know why and where this filter is used. 

However if the purpose of this filter is to return just packages exactly matching the systems architecture (e.g. x86_64) and not also compatible architectures (e.g. iX86,noarch), the patch is correct.

**Comment by DimStar77** [comment]
@hughsie if you could please confirm the intention of this filter? Also: I failed to find a documentation if it was to filter pri arch or compat arch.

**Comment by kalev** [comment]
AFAIK this should match both the main architecture (x86_64) + noarch and filter out the compat arch (i686)

**Comment by DimStar77** [comment]
So this patch is no good - it only shows main architecture (no noarch)

**Comment by kalev** [comment]
No, I mean, it should show noarch too

**Comment by DimStar77** [comment]
right - which is why this patch is no good :)

**Comment by kalev** [comment]
Ahh yes, right! :)

**Comment by DimStar77** [comment]
ok - now 'arch' filter shows "noarch" and "system primary architecture"

**Pull request merged**
