### PR TITLE
Add Nix as a backend

### PR DESCRIPTION
**Pull request by matthewbauer**
I'm going to put this here while I'm still working on it to get an early review if you can. I've implemented the barebones PackageKit vfuncs for Nix but it's still pretty buggy. If anyone can correct any obvious errors or issues that would be helpful. Right now, I've just been using pkcon and not any PackageKit GUI, so I'll have to figure that out as well.

### CODE REVIEW

**Comment by hughsie** [comment]
In concept looks good; I'm no C++ programmer but it looks a good start. If you want a real-world application to try, I'd suggest starting with gpk-application and gpk-update-viewer and then progress onto gnome-software. The former is quite demanding for status updates, and the latter needs requests to complete in lightning quick time. Yell if you need any sample AppStream data.

**Comment by matthewbauer** [comment]
I'm moving this to ready for review because I'm able to get everything working properly in "pkcon" and "gkp-application". There may still be some issues going forward. I'm not sure what your policy for adding new backends are but it's certainly in working condition right now.

I'm going to try to be working on generating the appstream data for NixOS, but it's unclear how to work with the way Nix packages stuff.

**Comment by ximion** [comment]
As long as the backend is maintained and working, we can have it in master - but talk to @hughsie about it, it might make sense to give you commit access to the repo so you can maintain the backend more easily.

> I'm going to try to be working on generating the appstream data for NixOS, but it's unclear how to work with the way Nix packages stuff.

Could you be more specific on that? Probably not the right place here though, a mail to appstream[at]lists.freedesktop.org is probably better (or a bug report against one of the AppStream metadata generators, in case you encounter a specific issue).

**Comment by hughsie** [comment]
Agreed, I'd rather you just have commit access if you want to be the maintainer for the nix backend.

**Comment by matthewbauer** [comment]
Pinging @edolstra, @domenkozar, for review of Nix related parts. Specifically, whether the "nix_get_all_derivations" and "nix_get_state" are properly working.

@ximion
Well eventually we are going to want to make an "appstream-builder" for the Nix build system that generates the appstream data. The issue right now is that there's not really a good way to tell between "apps" vs "non-apps" in Nix. In fact, there's not really an easy way to even tell what files are in a given derivation. Regardless, I think it's going to be easier getting PackageKit and related packages working first before tackling appstream.

**Comment by matthewbauer** [comment]
One more thing for @hughsie:

How is the arch part of "package id" used? Right now the way Nix encodes the "system" it looks like "x86_64-linux" or "i686-linux" while most of the other backends seem to just show "i686" or "x86_64". Is that data used anywhere besides just for display?

**Comment by hughsie** [comment]
@matthewbauer I think you can use the arch how you like.

**Comment by matthewbauer** [comment]
Okay, so this should be ready to merge then.

**Comment by hughsie** [comment]
I've given you commit access to master. Please push fixes to this backend only directly to master, and cherry pick them back into stable versions as appropriate. For any other fixes in the source tree please just grab a +1 from any of us. Thanks!

**Comment by matthewbauer** [comment]
Okay thanks!

**Pull request closed without merging**
